### ISSUE TITLE
Why are you bumping minimum php in patch releases?!

### ISSUE THREAD

**Issue by opengeek** [php-fig/container#42] opened 2022-03-08 17:12 UTC
This is literally a backward compatibility break and should never happen in a patch release.

**Comment by drealecs** [comment] 2022-03-08 19:36
How about minor? Can it happen in minor release? 😜

**Comment by Jean85** [comment] 2022-03-09 16:41
> This is literally a backward compatibility break and should never happen in a patch release.

No, it's not. You'll find a lengthy explanation in #41, and more concisely in https://github.com/php-fig/container/issues/41#issuecomment-972768920

TL;DR: if you run `composer update` in an environment that doesn't match your prod, you're on your own.

Closing as duplicate of #41.

**Closed as completed by Jean85** 2022-03-09 16:41 UTC
